[project]
name = "src"
version = "0.0.1"
description = "A MLOPs project for productionizing models"
authors = [{name = "vishwa",email = "vbsinsta9@gmail.com"}]

[tool.setuptools]
packages = {find = {}}

[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}